<<<<<<< HEAD
"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@material-tailwind/react";
const inter = Inter({ subsets: ["latin"] });

=======
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

>>>>>>> 0158647cb4f4c3a0860266ea7983739d9a840404
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<<<<<<< HEAD
    <ThemeProvider>
      <html lang="pt-br">
        <body className={`${inter.className} bg-white`}>{children}</body>
      </html>
    </ThemeProvider>
=======
    <html lang="pt-Br">
      <body className={`${inter.className} h-full w-full bg-black`}>
        {children}
      </body>
    </html>
>>>>>>> 0158647cb4f4c3a0860266ea7983739d9a840404
  );
}
